# Generated by Django 3.2 on 2021-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesScheduleAndResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_dt', models.DateTimeField(verbose_name='Game Date')),
                ('team1', models.CharField(max_length=25, verbose_name='Team1')),
                ('team2', models.CharField(max_length=25, verbose_name='Team2')),
                ('score', models.CharField(max_length=15, verbose_name='Game Score')),
                ('place', models.CharField(max_length=25, verbose_name='Game Place')),
            ],
            options={
                'verbose_name': 'Mad Game',
                'verbose_name_plural': 'Mad Games',
            },
        ),
        migrations.CreateModel(
            name='MadScheduleAndResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_dt', models.DateTimeField(verbose_name='Game Date')),
                ('team1', models.CharField(max_length=25, verbose_name='Team1')),
                ('team2', models.CharField(max_length=25, verbose_name='Team2')),
                ('score', models.CharField(max_length=15, verbose_name='Game Score')),
                ('place', models.CharField(max_length=25, verbose_name='Game Place')),
            ],
            options={
                'verbose_name': 'Mad Game',
                'verbose_name_plural': 'Mad Games',
            },
        ),
    ]
