# Generated by Django 3.2 on 2021-04-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('avg_point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='MadTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('avg_point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='OldTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('avg_point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='YoungTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('avg_point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='YoungPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=50, verbose_name='Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.madteam')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='YoungMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_result', models.IntegerField(verbose_name='team1 result')),
                ('t2_result', models.IntegerField(verbose_name='team2 result')),
                ('m_time', models.DateField(verbose_name='Match Time')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamOne', to='league.madteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamTwo', to='league.madteam')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='OldPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=50, verbose_name='Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.madteam')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='OldMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_result', models.IntegerField(verbose_name='team1 result')),
                ('t2_result', models.IntegerField(verbose_name='team2 result')),
                ('m_time', models.DateField(verbose_name='Match Time')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_One', to='league.madteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Two', to='league.madteam')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MadPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=50, verbose_name='Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.madteam')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='MadMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_result', models.IntegerField(verbose_name='team1 result')),
                ('t2_result', models.IntegerField(verbose_name='team2 result')),
                ('m_time', models.DateField(verbose_name='Match Time')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='league.madteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='league.madteam')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='LesPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=50, verbose_name='Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.madteam')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='LesMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_result', models.IntegerField(verbose_name='team1 result')),
                ('t2_result', models.IntegerField(verbose_name='team2 result')),
                ('m_time', models.DateField(verbose_name='Match Time')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='league.madteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='league.madteam')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
    ]
