# Generated by Django 3.2 on 2021-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadScheduleAndResults2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_dt', models.DateTimeField(verbose_name='Game Date')),
                ('team1', models.CharField(max_length=25, verbose_name='Team1')),
                ('team2', models.CharField(max_length=25, verbose_name='Team2')),
                ('score', models.CharField(max_length=15, verbose_name='Game Score')),
                ('place', models.CharField(max_length=25, verbose_name='Game Place')),
            ],
            options={
                'verbose_name': 'Mad Game 20-21',
                'verbose_name_plural': 'Mad Games 20-21',
            },
        ),
        migrations.CreateModel(
            name='MadScheduleAndResults2122',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_dt', models.DateTimeField(verbose_name='Game Date')),
                ('team1', models.CharField(max_length=25, verbose_name='Team1')),
                ('team2', models.CharField(max_length=25, verbose_name='Team2')),
                ('score', models.CharField(max_length=15, verbose_name='Game Score')),
                ('place', models.CharField(max_length=25, verbose_name='Game Place')),
            ],
            options={
                'verbose_name': 'Mad Game 21-22',
                'verbose_name_plural': 'Mad Games 21-22',
            },
        ),
        migrations.RenameModel(
            old_name='MadScheduleAndResults',
            new_name='LesScheduleAndResults2021',
        ),
        migrations.RenameModel(
            old_name='LesScheduleAndResults',
            new_name='LesScheduleAndResults2122',
        ),
        migrations.AlterModelOptions(
            name='lesscheduleandresults2021',
            options={'verbose_name': 'Les Game 20-21', 'verbose_name_plural': 'Les Games 20-21'},
        ),
        migrations.AlterModelOptions(
            name='lesscheduleandresults2122',
            options={'verbose_name': 'Les Game 21-22', 'verbose_name_plural': 'Les Games 21-22'},
        ),
    ]
