# Generated by Django 3.2 on 2021-04-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesmatches',
            options={'verbose_name': 'match(Les)', 'verbose_name_plural': 'matches(Les)'},
        ),
        migrations.AlterModelOptions(
            name='lesplayers',
            options={'verbose_name': 'player(Les)', 'verbose_name_plural': 'players(Les)'},
        ),
        migrations.AlterModelOptions(
            name='lesteam',
            options={'verbose_name': 'team(Les)', 'verbose_name_plural': 'teams(Les)'},
        ),
        migrations.AlterModelOptions(
            name='madmatches',
            options={'verbose_name': 'match(Mad)', 'verbose_name_plural': 'matches(Mad)'},
        ),
        migrations.AlterModelOptions(
            name='madplayers',
            options={'verbose_name': 'player(Mad)', 'verbose_name_plural': 'players(Mad)'},
        ),
        migrations.AlterModelOptions(
            name='madteam',
            options={'verbose_name': 'team(Mad)', 'verbose_name_plural': 'teams(Mad)'},
        ),
        migrations.AlterModelOptions(
            name='oldmatches',
            options={'verbose_name': 'match(Old)', 'verbose_name_plural': 'matches(Old)'},
        ),
        migrations.AlterModelOptions(
            name='oldplayers',
            options={'verbose_name': 'player(Old)', 'verbose_name_plural': 'players(Old)'},
        ),
        migrations.AlterModelOptions(
            name='oldteam',
            options={'verbose_name': 'team(Old)', 'verbose_name_plural': 'teams(Old)'},
        ),
        migrations.AlterModelOptions(
            name='youngmatches',
            options={'verbose_name': 'match(Young)', 'verbose_name_plural': 'matches(Young)'},
        ),
        migrations.AlterModelOptions(
            name='youngplayers',
            options={'verbose_name': 'player(Young)', 'verbose_name_plural': 'players(Young)'},
        ),
        migrations.AlterModelOptions(
            name='youngteam',
            options={'verbose_name': 'team(Young)', 'verbose_name_plural': 'teams(Young)'},
        ),
    ]
