# Generated by Django 3.2 on 2021-04-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210422_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesmatches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='league.lesteam'),
        ),
        migrations.AlterField(
            model_name='lesmatches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='league.lesteam'),
        ),
        migrations.AlterField(
            model_name='youngmatches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamOne', to='league.youngteam'),
        ),
        migrations.AlterField(
            model_name='youngmatches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamTwo', to='league.youngteam'),
        ),
    ]
