# Generated by Django 3.2 on 2021-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20210424_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesmatches',
            name='t1_result',
            field=models.IntegerField(default=0, verbose_name='team1 result'),
        ),
        migrations.AlterField(
            model_name='lesmatches',
            name='t2_result',
            field=models.IntegerField(default=0, verbose_name='team2 result'),
        ),
    ]
