# Generated by Django 3.2 on 2021-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20210425_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aleagueregular',
            name='win_lose',
        ),
        migrations.RemoveField(
            model_name='aleaguesemifinal',
            name='win_lose',
        ),
        migrations.RemoveField(
            model_name='womenchampionship',
            name='win_lose',
        ),
        migrations.AddField(
            model_name='aleagueregular',
            name='lose',
            field=models.IntegerField(default=0, verbose_name='Lose'),
        ),
        migrations.AddField(
            model_name='aleagueregular',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Won'),
        ),
        migrations.AddField(
            model_name='aleaguesemifinal',
            name='lose',
            field=models.IntegerField(default=0, verbose_name='Lose'),
        ),
        migrations.AddField(
            model_name='aleaguesemifinal',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Won'),
        ),
        migrations.AddField(
            model_name='womenchampionship',
            name='lose',
            field=models.IntegerField(default=0, verbose_name='Lose'),
        ),
        migrations.AddField(
            model_name='womenchampionship',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Won'),
        ),
    ]
