# Generated by Django 3.2 on 2021-04-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=30, verbose_name='Name')),
                ('sh_number', models.IntegerField(verbose_name='Shirt number')),
                ('g_played', models.IntegerField(verbose_name='Games Played')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth date')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Les player',
                'verbose_name_plural': 'Les players',
            },
        ),
        migrations.CreateModel(
            name='LesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('games_played', models.IntegerField(verbose_name='Games')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Team with Les Foxes',
                'verbose_name_plural': 'Teams with Les Foxes',
            },
        ),
        migrations.CreateModel(
            name='MadPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=30, verbose_name='Name')),
                ('sh_number', models.IntegerField(verbose_name='Shirt number')),
                ('g_played', models.IntegerField(verbose_name='Games Played')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth date')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Mad player',
                'verbose_name_plural': 'Mad players',
            },
        ),
        migrations.CreateModel(
            name='MadTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('games_played', models.IntegerField(verbose_name='Games')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Team with Mad Foxes',
                'verbose_name_plural': 'Teams with Mad Foxes',
            },
        ),
        migrations.CreateModel(
            name='OldPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=30, verbose_name='Name')),
                ('sh_number', models.IntegerField(verbose_name='Shirt number')),
                ('g_played', models.IntegerField(verbose_name='Games Played')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth date')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Old player',
                'verbose_name_plural': 'Old players',
            },
        ),
        migrations.CreateModel(
            name='OldTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('games_played', models.IntegerField(verbose_name='Games')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Team with Old Foxes',
                'verbose_name_plural': 'Teams with Old Foxes',
            },
        ),
        migrations.CreateModel(
            name='YoungPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fullname', models.CharField(max_length=30, verbose_name='Name')),
                ('sh_number', models.IntegerField(verbose_name='Shirt number')),
                ('g_played', models.IntegerField(verbose_name='Games Played')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth date')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Young player',
                'verbose_name_plural': 'Young players',
            },
        ),
        migrations.CreateModel(
            name='YoungTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, verbose_name='Team')),
                ('games_played', models.IntegerField(verbose_name='Games')),
                ('pts', models.IntegerField(verbose_name='PTS')),
                ('avg_point', models.IntegerField(verbose_name='Average')),
            ],
            options={
                'verbose_name': 'Team with Young Foxes',
                'verbose_name_plural': 'Teams with Young Foxes',
            },
        ),
        migrations.CreateModel(
            name='MadTopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='points per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.madplayers')),
            ],
            options={
                'verbose_name': 'Mad Top Scorer',
            },
        ),
        migrations.CreateModel(
            name='MadTopRebounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='rebounds per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.madplayers')),
            ],
            options={
                'verbose_name': 'Mad Top Rebounder',
            },
        ),
        migrations.CreateModel(
            name='MadTopAssister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='assists per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.madplayers')),
            ],
            options={
                'verbose_name': 'Mad Top Assister',
            },
        ),
        migrations.CreateModel(
            name='LesTopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='points per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.lesplayers')),
            ],
            options={
                'verbose_name': 'Les Top Scorer',
            },
        ),
        migrations.CreateModel(
            name='LesTopRebounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='rebounds per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.lesplayers')),
            ],
            options={
                'verbose_name': 'Les Top Rebounder',
            },
        ),
        migrations.CreateModel(
            name='LesTopAssister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='assists per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_team.lesplayers')),
            ],
            options={
                'verbose_name': 'Les Top Assister',
            },
        ),
    ]
