# Generated by Django 3.2 on 2021-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=35, verbose_name='Name')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
            ],
            options={
                'verbose_name': "Les Player's Roster",
                'verbose_name_plural': "Les Players's Rosters",
            },
        ),
        migrations.CreateModel(
            name='MadRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=35, verbose_name='Name')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
            ],
            options={
                'verbose_name': "Mad Player's Roster",
                'verbose_name_plural': "Mad Players's Rosters",
            },
        ),
    ]
